%
% Compute a spectral network statistic for a full dataset.
%
% PARAMETERS 
%	$statistic
%	$decomposition
%	$network
%
% INPUT 
%	dat/info.$network
%	dat/decomposition.$decomposition.$network.mat
%
% OUTPUT 
%	dat/statistic.$statistic.$network
%		Same format as generated by statistic_comp.m
%

network = getenv('network');
statistic = getenv('statistic');
decomposition = getenv('decomposition');

info = read_info(network); 

data_decomposition = load(sprintf('dat/decomposition.%s.%s.mat', decomposition, network)); 

values = statistic_spectral(statistic, data_decomposition.D, data_decomposition.n);

save(sprintf('dat/statistic.%s.%s', statistic, network), 'values', '-ascii'); 
