#! /bin/sh
#
# Wrapper for running Julia scripts. 
#

TMPDIR="${TMPDIR-/tmp}"

log="$TMPDIR/julia"

name="$(basename "$1" | sed -E -e 's,\.jl$,,')"

log="$log.$name"

[ "$network" ] && log="$log"."$network"

log="$log.log"

julia "$1" "$log" >"$log" 2>&1 
