#! /bin/sh
#
# Execute Stu parallely, dividing used memory by K, and limiting
# runtime of processes.  Also, be NICE.
#
# In order to limit the memory used by KONECT processes, use
#
#    ulimit -v SIZE
#
# where SIZE is the amount of memory that should be used, in kilobytes.  
#
# INVOCATION 
#	$0 [K] args...
#		K is the number of processes to run in parallel; if not
#		given, defaults to a single process 
#
# PARAMETERS
#	$MN_RUNTIME	Maximal runtime in hours; if not set, don't
#			limit runtime 
#

K=1

[ "$1" ] && echo "$1" | grep '^[0-9]*$' >/dev/null && {
	K="$1"
	shift 
}

rm -f error.log 

if [ "$MN_RUNTIME" ] ; then 
	RUNTIME_S="`expr $MN_RUNTIME '*' 3600`"
	ulimit -t "$RUNTIME_S"
fi 

exec nice sh/mem "$K" stu -j "$K" "$@"
