#! /bin/sh
#
# Show the currently running processes started with ./{octave,matlab,julia}.
# This calls ps(1) and presents the results in a nice way.   
#
# All shown runtimes are CPU times, not wall clock times. 
#
# MECHANISM 
#
# To show the time left for a task, a program outputs, at regular
# intervals, strings of the form
#
#     [TIMESPEC left]
#
# where TIMESPEC is the time left in free form.  The string does not
# need to be alone on a line. 
#

# Format for the printf(1) command
format='%4s %10s %11s %13s %s\n'

# Header line
printf "$format" "%CPU" "Mem [k]" "Runtime" "Runtime left" "Log"

TMPDIR="${TMPDIR-/tmp}"
TMPDIR_esc="$(echo "$TMPDIR" | sed -E -e 's,/,\\/,g')"

ps k-cputime -o %cpu,cputime,vsize,user,command | 
sed -E -e '1d;/'"$TMPDIR_esc"'/!d' |
while IFS= read -r line
do
	cpu="$(echo "$line" | sed -E -e 's,^\s*(\S+)\s.*$,\1,;s,\.[0-9]$,,')" 
	vsize="$(echo "$line" | sed -E -e 's,^\s*\S+\s+\S+\s+(\S+)\s.*$,\1,')"
	time="$(echo "$line" | sed -E -e 's,^\s*,,' | cut -f 2 -d ' ' | sed -E -e 's,^[0:]*(.*....)$,\1,')"
	logfile="$(echo "$line" | sed -E -e 's,^.*\s('"$TMPDIR_esc"'\S+).*$,\1,')"

	command="$(echo "$line" | sed -E -e 's,^\s*\S+\s+\S+\s+\S+\s+\S+\s+(\S+)\s.*$,\1,')"
	command="$(basename "$command")"

	# Don't show clearly non-computational processes.  For instance,
	# 'less' is often used to look at logfiles. 
	if [ "$command" = less ] || [ "$command" = more ] || [ "$command" = tail ] || [ "$command" = sed ] ; then
		continue
	fi
	if printf "%s\n" "$command" | grep -E ^main.stu >/dev/null ; then
		continue
	fi
	
	# 'tac' may report an error if the logfile was not (yet)
	# created.  Ignore this error.  
	left="$(tac "$logfile" 2>/dev/null | sed -E -e '/left]/!d;s,^.*\[(.*) left\].*$,\1,;q')"
	if [ -z "$left" ] ; then
		# If there is a time left informatioln available
		# for a sub-task, show that prefixed with '+'. 
		left="$(tac "$logfile" 2>/dev/null | sed -E -e '/left}/!d;s,^.*\{(.*) left\}.*$,+\1,;q')"
	fi

	logfile_color="$(echo "$logfile" | sed -E -e 's,^(.*)/([^.]+)\.(.+).log$,\1/\2.[1m\3[m.log,')"
	
	printf "$format" "$cpu" "$vsize" "$time" "$left" "$logfile_color"
done				
