#! /bin/sh
#
# Filter networks by their category.
#
# PARAMETERS 
#	$category	Name of the category
#
# STDIN 
#	One network name per line
#
# STDOUT 
#	One network name per line, containing only those networks that
#	are in the given category 
#

while read network
do
    if grep -qE '^\s*category\s*:\s*'"$category"'\s*$' uni/meta."$network"
    then
	echo "$network"
    fi
done
