#! /bin/sh
#
# Output the dependencies of a network. 
#
# The list of dependencies is output in the order in which it is build,
# which is the same order as things are defined in the KONECT Handbook.  
#
# PARAMETERS
#	$network
#	$plots_only	Non-empty when only plots should be output 
#
# STDOUT
#	The list of dependencies in Stu format
#
# INPUT FILES
#	dat/dep.statistic.all.$network
#	dat/dep.plot.all.$network
#	PLOTS
#	PLOTS_SQUARE
#	PLOTS_ASYM
#	PLOTS_TIME
#	dat/NETWORKS_$attribute  for all attributes
#

set -e

#
# Tests
#

echo @check."$network"

#
# Data files 
#

echo @tsv."$network"

#
# Statistics
#

cat dat/dep.statistic.all."$network"

#
# Features
#

# Disabled because it does not work for all network types (C code)
## echo @ft.degree."$network" 

#
# Plots
#

cat dat/dep.plot.all."$network"
