#! /bin/sh
#
# Generate the dependencies of a network, excluding the @check
# computation.  
#
# PARAMETERS
#	$network
#	$plots_only
#
# STDOUT
#	The list of dependencies in Stu format
#
# INPUT FILES
#	PLOTS
#	PLOTS_SQUARE
#	PLOTS_ASYM
#	PLOTS_TIME
#	dat/NETWORKS_$attribute
#	dat/dep.statistic-network.$network
#

#
# Plots
#

for PLOT in $(cat PLOTS) ; do
	echo @"$PLOT"."$network"
done

if grep -q '^'"$network"'$' dat/NETWORKS_SQUARE ; then
	for PLOT in $(cat PLOTS_SQUARE) ; do 
		echo @"$PLOT"."$network"
	done
fi

if grep -q '^'"$network"'$' dat/NETWORKS_ASYM ; then
	for PLOT in $(cat PLOTS_ASYM) ; do 
		echo @"$PLOT"."$network"
	done
fi

if grep -q '^'"$network"'$' dat/NETWORKS_TIME ; then
	for PLOT in $(cat PLOTS_TIME) ; do 
		echo @"$PLOT"."$network"
	done
fi

if [ "$plots_only" ] ; then
	exit 0
fi

#
# Statistics
#

cat dat/dep.statistic-network."$network"

#
# Features
#

# Disabled because it does not work for all network types (C code)
## echo @ft.degree."$network" 

#
# Data files 
#

echo @tsv."$network"

