#! /bin/sh
#
# Compute C/C++ dependencies.
#
# INVOCATION 
#	$0 $FILENAME
#
# STDOUT
#	The needed files, one per line
#

set -e

TMPDIR="${TMPDIR:-/tmp}"
TMPFILE="$TMPDIR/depc.$$"

echo "$1" >"$TMPFILE"

while :
do
	rm -f "$TMPFILE".new
	r=0
	for file in $(cat "$TMPFILE")
	do
		r=1
		echo "$file"
		if [ -e "$file" ]; then
			<"$file" >>"$TMPFILE".new sed -E -e 's,^\s*#\s*include\s+"(.*)",c/\1,;t;d'
		fi
	done
	if [ "$r" = 0 ]; then  exit 0;  fi
	cp "$TMPFILE".new "$TMPFILE" 
done |
sort -u 
