#! /bin/sh
#
# Divide the 'ulimit -v' value by SIZE and execute COMMAND.  ulimit -v
# must be set to a finite value, or be 'unlimited'.
#
# 'ulimit -v' is used to limit the amount of memory usable by each
# process.  
#
# INVOCATION 
# 
#	$0 SIZE COMMAND
#

size=$1
shift

mem=$(echo $(ulimit -v))

if [ "$mem" = unlimited ]
then
	# There is no limit -- just execute the command
	exec "$@"
else
	ulimit -v "$((mem / size))"
	exec "$@"
fi
