#! /bin/sh
#
# Generate list of networks.
#
# INPUT FILES
#	uni/*
#
# STDOUT
#	One network per line:
#
#	NETWORK <space> FORMAT <space> WEIGHTS <space> TIMESTAMPS <space> BYTES
#
#	TIMESTAMPS is t for timestamps and 0 for no timestamps 
#	BYTES is the size in bytes.
#	Entries are not sorted. 
#
# ENVIRONMENT 
#
#	$verbose	Set to non-empty for verbose mode
#

[ "$verbose" ] && exec 4>&2 || exec 4>/dev/null 

echo uni/out.* | sed -e 's| \{1,\}|\
|g' |
while IFS= read -r file
do
	echo >&4 "file='$file'"
	name="$(echo "$file" | sed -e 's,^uni/out\.,,')"
	echo >&4 "name='$name'"
	
	# Name, format and weight
	printf '%s' "$name $(head -1 "$file" | sed -E -e 's,^.* ([^ ]+) .*$,\1,') $(head -1 "$file" | sed -E -e 's,^.*\s([^ ]+)\s*$,\1,') "

	# Timestamps
	if [ $(head "$file" | tail -1 | wc -w) -gt 3 ]
	then
		printf t
	else
		printf 0
	fi
	printf ' ' 

	# Bytes
	ls -lH -- "$file" | cut -d ' ' -f 5 
done
