#! /bin/sh
#
# Output the value of $MATLABPATH. 
#

printf "$PWD/m/:$PWD/konect-toolbox/m:$PWD/lib/:$PWD/lib/matlab_bgl/:$PWD/lib/wafo-statistics/:$PWD/lib/wafo-misc/:$PWD/lib/gridxy:$PWD/syngraphy/" 
