#! /bin/sh
#
# Extract last eigenvalues calculated.
#
# PARAMETERS
#		$1	name of logfile
#
# INPUT:  $1
# OUTPUT: Output the values on stdout 
#

tail -n900 $1 | tac | sed -e '/^Iteration/Q' | tac | sed -re '/^\s*[e+0-9.]+\s*$/!Q'


