#! /bin/sh
#
# Output all statistic targets for $network.
#
# INPUT FILES
#	STATISTICS
#	GROUPS
#	dat/NETWORKS_$group  for all groups
#	konect-toolbox/m/konect_statistic_$statistic.m
#

for statistic in $(cat STATISTICS) ; do
	# check whether the statistic must be computed for this network 
	compute=1
	file="konect-toolbox/m/konect_statistic_$statistic.m"
	if [ -r "$file" ] ; then
		for group in $(<"$file" sed -E -e 's,^.*GROUP\s*:,,;t;d' | tr a-z A-Z) ; do
			if ! grep -q -E '^\s*'"$group"'\s*$' GROUPS ; then
				echo >&2 "$file:  unknown group '$group' (1)" 
				exit 1
			fi
			if [ ! -r dat/NETWORKS_"$group" ] ; then 
				echo >&2 "$file:  unknown group '$group' (2)" 
				exit 1
			fi
			if ! grep -Eq '^'"$network"'$' "dat/NETWORKS_$group" ; then
				compute=0
			fi
		done
	else
		: # Nothing.  Not all statistics have a file in the toolbox. 
	fi
		
	if [ "$compute" != 0 ] ; then
		echo @statistic."$statistic"."$network"
	fi
done
